/*
Pentagonal numbers are generated by the formula, Pn=n(3n?1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 ? 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk ? Pj|
is minimised; what is the value of D?
 */
public class Problem44 {
    public static void main(String[] args) {
        int n = 1;
        int Pk, Pj;
        System.out.println(isPenta(13));
        loop: while (true) {
            Pk = n * (3 * n - 1) / 2;
            for (int j = n - 1; j > 0; j--) {
                Pj = j * (3 * j - 1) / 2;
                if (isPenta(Pk + Pj) && isPenta(Pk - Pj)) {
                    System.out.println(n + " " + j);
                    System.out.println(Pk - Pj);
                    break loop;
                }
            }
            n++;
        }
    }

    private static boolean isPenta(int x) {
        double penTest = (Math.sqrt(1 + 24 * x) + 1.0) / 6.0;
        return penTest == ((int)penTest);
    }
}
